
name: Ari R. Kamlani
title: Ari R. Kamlani
simple_search: http://google.com/search
description: Personal Site of Ari R. Kamlani
url: http://arikamlani.com

author:
   name: Ari R. Kamlani
   email: akamlani@gmail.com

safe: false
lsi: false
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
markdown: kramdown 

languages: [en]

exclude:
- README.md

