
name: Ari Kamlani
title: Ari Kamlani
simple_search: http://google.com/search
description: Personal Site of Ari Kamlani
url: https://www.arikamlani.com

author:
   name: Ari Kamlani
   email: akamlani@gmail.com

safe: false
lsi: false
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
markdown: kramdown 

languages: [en]

exclude:
- README.md

