
name: Ari R. Kamlani
title: Ari R. Kamlani
simple_search: http://google.com/search
description: Personal Site of Ari R. Kamlani
url: http://arikamlani.com

author: 
   name: Ari R. Kamlani

paginate: 2
paginate_path: "blogs/jekyll/page:num"


safe: false
lsi: false
pygments: true
permalink: /blogs/jekyll/:year/:month/:day/:title
markdown: rdiscount


#archive:
#    layout: archive
#    path: /blogs/jekyll
#    title: Blog Archive - :date

archive_path: blogs/jekyll/archives



tag_page_layout: tag_page
tag_page_dir: blogs/jekyll/tag

tag_feed_layout: tag_feed
tag_feed_dir: blogs/jekyll/feeds

languages: [en]



