
name: Ari R. Kamlani
title: Ari R. Kamlani
simple_search: http://google.com/search
description: Personal Site of Ari R. Kamlani
base_url: http://arikamlani.com

author: 
   name: Ari R. Kamlani

paginate: 1

safe: false
lsi: false
pygments: true
permalink: /blogs/jekyll/:year/:month/:day/:title
markdown: rdiscount

tag_page_layout: tag_page
tag_page_dir: blogs/jekyll/tag

tag_feed_layout: tag_feed
tag_feed_dir: blogs/jekyll/feeds


languages: [en]

